/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmFatorRouteImport } from './routes/um-fator'
import { Route as TresFatoresRouteImport } from './routes/tres-fatores'
import { Route as SuperTrunfoRouteImport } from './routes/super-trunfo'
import { Route as SmartMoveRouteImport } from './routes/smart-move'
import { Route as SalaRotativaUmFatorRouteImport } from './routes/sala-rotativa-um-fator'
import { Route as SalaRotativaRouteImport } from './routes/sala-rotativa'
import { Route as Ruas25pctRouteImport } from './routes/ruas-25pct'
import { Route as Ruas10pctRouteImport } from './routes/ruas-10pct'
import { Route as RuasRouteImport } from './routes/ruas'
import { Route as Numeros28pctRouteImport } from './routes/numeros-28pct'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as FootballBlitzRouteImport } from './routes/football-blitz'
import { Route as DoisFatoresRouteImport } from './routes/dois-fatores'
import { Route as DocCalculadoraRouletteRouteImport } from './routes/doc-calculadora-roulette'
import { Route as DamasRouteImport } from './routes/damas'
import { Route as CasinoMesaRouteImport } from './routes/casino-mesa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as MobileUm1fatorRouteImport } from './routes/mobile/um1fator'
import { Route as MobilePerfilRouteImport } from './routes/mobile/perfil'
import { Route as MobileDois2fatoresRouteImport } from './routes/mobile/dois2fatores'
import { Route as ApiRawRouteImport } from './routes/api/raw'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiDamasRouteImport } from './routes/api/damas'
import { Route as ApiRouletteStrategyGlobalRouteImport } from './routes/api/roulette/strategy-global'
import { Route as ApiRouletteSpinsRouteImport } from './routes/api/roulette/spins'
import { Route as ApiPragmaticFootballBlitzSpinsRouteImport } from './routes/api/pragmatic/football-blitz-spins'
import { Route as ApiPragmatic24dSpinSpinsRouteImport } from './routes/api/pragmatic/24d-spin-spins'
import { Route as MobileRoletaMesaIdIndexRouteImport } from './routes/mobile/roleta/$mesaId/index'
import { Route as MobileRoletaMesaIdUm1fatorRouteImport } from './routes/mobile/roleta/$mesaId/um1fator'
import { Route as MobileRoletaMesaIdDois2fatoresRouteImport } from './routes/mobile/roleta/$mesaId/dois2fatores'
import { Route as ApiRouletteStrategyGlobalStreamRouteImport } from './routes/api/roulette/strategy-global.stream'
import { Route as ApiRouletteStrategyGlobalResetRouteImport } from './routes/api/roulette/strategy-global.reset'

const UmFatorRoute = UmFatorRouteImport.update({
  id: '/um-fator',
  path: '/um-fator',
  getParentRoute: () => rootRouteImport,
} as any)
const TresFatoresRoute = TresFatoresRouteImport.update({
  id: '/tres-fatores',
  path: '/tres-fatores',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperTrunfoRoute = SuperTrunfoRouteImport.update({
  id: '/super-trunfo',
  path: '/super-trunfo',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMoveRoute = SmartMoveRouteImport.update({
  id: '/smart-move',
  path: '/smart-move',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRotativaUmFatorRoute = SalaRotativaUmFatorRouteImport.update({
  id: '/sala-rotativa-um-fator',
  path: '/sala-rotativa-um-fator',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRotativaRoute = SalaRotativaRouteImport.update({
  id: '/sala-rotativa',
  path: '/sala-rotativa',
  getParentRoute: () => rootRouteImport,
} as any)
const Ruas25pctRoute = Ruas25pctRouteImport.update({
  id: '/ruas-25pct',
  path: '/ruas-25pct',
  getParentRoute: () => rootRouteImport,
} as any)
const Ruas10pctRoute = Ruas10pctRouteImport.update({
  id: '/ruas-10pct',
  path: '/ruas-10pct',
  getParentRoute: () => rootRouteImport,
} as any)
const RuasRoute = RuasRouteImport.update({
  id: '/ruas',
  path: '/ruas',
  getParentRoute: () => rootRouteImport,
} as any)
const Numeros28pctRoute = Numeros28pctRouteImport.update({
  id: '/numeros-28pct',
  path: '/numeros-28pct',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballBlitzRoute = FootballBlitzRouteImport.update({
  id: '/football-blitz',
  path: '/football-blitz',
  getParentRoute: () => rootRouteImport,
} as any)
const DoisFatoresRoute = DoisFatoresRouteImport.update({
  id: '/dois-fatores',
  path: '/dois-fatores',
  getParentRoute: () => rootRouteImport,
} as any)
const DocCalculadoraRouletteRoute = DocCalculadoraRouletteRouteImport.update({
  id: '/doc-calculadora-roulette',
  path: '/doc-calculadora-roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const DamasRoute = DamasRouteImport.update({
  id: '/damas',
  path: '/damas',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoMesaRoute = CasinoMesaRouteImport.update({
  id: '/casino-mesa',
  path: '/casino-mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const MobileUm1fatorRoute = MobileUm1fatorRouteImport.update({
  id: '/um1fator',
  path: '/um1fator',
  getParentRoute: () => MobileRoute,
} as any)
const MobilePerfilRoute = MobilePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MobileRoute,
} as any)
const MobileDois2fatoresRoute = MobileDois2fatoresRouteImport.update({
  id: '/dois2fatores',
  path: '/dois2fatores',
  getParentRoute: () => MobileRoute,
} as any)
const ApiRawRoute = ApiRawRouteImport.update({
  id: '/api/raw',
  path: '/api/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDamasRoute = ApiDamasRouteImport.update({
  id: '/api/damas',
  path: '/api/damas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouletteStrategyGlobalRoute =
  ApiRouletteStrategyGlobalRouteImport.update({
    id: '/api/roulette/strategy-global',
    path: '/api/roulette/strategy-global',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRouletteSpinsRoute = ApiRouletteSpinsRouteImport.update({
  id: '/api/roulette/spins',
  path: '/api/roulette/spins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPragmaticFootballBlitzSpinsRoute =
  ApiPragmaticFootballBlitzSpinsRouteImport.update({
    id: '/api/pragmatic/football-blitz-spins',
    path: '/api/pragmatic/football-blitz-spins',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPragmatic24dSpinSpinsRoute =
  ApiPragmatic24dSpinSpinsRouteImport.update({
    id: '/api/pragmatic/24d-spin-spins',
    path: '/api/pragmatic/24d-spin-spins',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileRoletaMesaIdIndexRoute = MobileRoletaMesaIdIndexRouteImport.update({
  id: '/roleta/$mesaId/',
  path: '/roleta/$mesaId/',
  getParentRoute: () => MobileRoute,
} as any)
const MobileRoletaMesaIdUm1fatorRoute =
  MobileRoletaMesaIdUm1fatorRouteImport.update({
    id: '/roleta/$mesaId/um1fator',
    path: '/roleta/$mesaId/um1fator',
    getParentRoute: () => MobileRoute,
  } as any)
const MobileRoletaMesaIdDois2fatoresRoute =
  MobileRoletaMesaIdDois2fatoresRouteImport.update({
    id: '/roleta/$mesaId/dois2fatores',
    path: '/roleta/$mesaId/dois2fatores',
    getParentRoute: () => MobileRoute,
  } as any)
const ApiRouletteStrategyGlobalStreamRoute =
  ApiRouletteStrategyGlobalStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiRouletteStrategyGlobalRoute,
  } as any)
const ApiRouletteStrategyGlobalResetRoute =
  ApiRouletteStrategyGlobalResetRouteImport.update({
    id: '/reset',
    path: '/reset',
    getParentRoute: () => ApiRouletteStrategyGlobalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casino-mesa': typeof CasinoMesaRoute
  '/damas': typeof DamasRoute
  '/doc-calculadora-roulette': typeof DocCalculadoraRouletteRoute
  '/dois-fatores': typeof DoisFatoresRoute
  '/football-blitz': typeof FootballBlitzRoute
  '/mobile': typeof MobileRouteWithChildren
  '/numeros-28pct': typeof Numeros28pctRoute
  '/ruas': typeof RuasRoute
  '/ruas-10pct': typeof Ruas10pctRoute
  '/ruas-25pct': typeof Ruas25pctRoute
  '/sala-rotativa': typeof SalaRotativaRoute
  '/sala-rotativa-um-fator': typeof SalaRotativaUmFatorRoute
  '/smart-move': typeof SmartMoveRoute
  '/super-trunfo': typeof SuperTrunfoRoute
  '/tres-fatores': typeof TresFatoresRoute
  '/um-fator': typeof UmFatorRoute
  '/api/damas': typeof ApiDamasRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/mobile/dois2fatores': typeof MobileDois2fatoresRoute
  '/mobile/perfil': typeof MobilePerfilRoute
  '/mobile/um1fator': typeof MobileUm1fatorRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/pragmatic/24d-spin-spins': typeof ApiPragmatic24dSpinSpinsRoute
  '/api/pragmatic/football-blitz-spins': typeof ApiPragmaticFootballBlitzSpinsRoute
  '/api/roulette/spins': typeof ApiRouletteSpinsRoute
  '/api/roulette/strategy-global': typeof ApiRouletteStrategyGlobalRouteWithChildren
  '/api/roulette/strategy-global/reset': typeof ApiRouletteStrategyGlobalResetRoute
  '/api/roulette/strategy-global/stream': typeof ApiRouletteStrategyGlobalStreamRoute
  '/mobile/roleta/$mesaId/dois2fatores': typeof MobileRoletaMesaIdDois2fatoresRoute
  '/mobile/roleta/$mesaId/um1fator': typeof MobileRoletaMesaIdUm1fatorRoute
  '/mobile/roleta/$mesaId/': typeof MobileRoletaMesaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casino-mesa': typeof CasinoMesaRoute
  '/damas': typeof DamasRoute
  '/doc-calculadora-roulette': typeof DocCalculadoraRouletteRoute
  '/dois-fatores': typeof DoisFatoresRoute
  '/football-blitz': typeof FootballBlitzRoute
  '/numeros-28pct': typeof Numeros28pctRoute
  '/ruas': typeof RuasRoute
  '/ruas-10pct': typeof Ruas10pctRoute
  '/ruas-25pct': typeof Ruas25pctRoute
  '/sala-rotativa': typeof SalaRotativaRoute
  '/sala-rotativa-um-fator': typeof SalaRotativaUmFatorRoute
  '/smart-move': typeof SmartMoveRoute
  '/super-trunfo': typeof SuperTrunfoRoute
  '/tres-fatores': typeof TresFatoresRoute
  '/um-fator': typeof UmFatorRoute
  '/api/damas': typeof ApiDamasRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/mobile/dois2fatores': typeof MobileDois2fatoresRoute
  '/mobile/perfil': typeof MobilePerfilRoute
  '/mobile/um1fator': typeof MobileUm1fatorRoute
  '/mobile': typeof MobileIndexRoute
  '/api/pragmatic/24d-spin-spins': typeof ApiPragmatic24dSpinSpinsRoute
  '/api/pragmatic/football-blitz-spins': typeof ApiPragmaticFootballBlitzSpinsRoute
  '/api/roulette/spins': typeof ApiRouletteSpinsRoute
  '/api/roulette/strategy-global': typeof ApiRouletteStrategyGlobalRouteWithChildren
  '/api/roulette/strategy-global/reset': typeof ApiRouletteStrategyGlobalResetRoute
  '/api/roulette/strategy-global/stream': typeof ApiRouletteStrategyGlobalStreamRoute
  '/mobile/roleta/$mesaId/dois2fatores': typeof MobileRoletaMesaIdDois2fatoresRoute
  '/mobile/roleta/$mesaId/um1fator': typeof MobileRoletaMesaIdUm1fatorRoute
  '/mobile/roleta/$mesaId': typeof MobileRoletaMesaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casino-mesa': typeof CasinoMesaRoute
  '/damas': typeof DamasRoute
  '/doc-calculadora-roulette': typeof DocCalculadoraRouletteRoute
  '/dois-fatores': typeof DoisFatoresRoute
  '/football-blitz': typeof FootballBlitzRoute
  '/mobile': typeof MobileRouteWithChildren
  '/numeros-28pct': typeof Numeros28pctRoute
  '/ruas': typeof RuasRoute
  '/ruas-10pct': typeof Ruas10pctRoute
  '/ruas-25pct': typeof Ruas25pctRoute
  '/sala-rotativa': typeof SalaRotativaRoute
  '/sala-rotativa-um-fator': typeof SalaRotativaUmFatorRoute
  '/smart-move': typeof SmartMoveRoute
  '/super-trunfo': typeof SuperTrunfoRoute
  '/tres-fatores': typeof TresFatoresRoute
  '/um-fator': typeof UmFatorRoute
  '/api/damas': typeof ApiDamasRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/mobile/dois2fatores': typeof MobileDois2fatoresRoute
  '/mobile/perfil': typeof MobilePerfilRoute
  '/mobile/um1fator': typeof MobileUm1fatorRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/pragmatic/24d-spin-spins': typeof ApiPragmatic24dSpinSpinsRoute
  '/api/pragmatic/football-blitz-spins': typeof ApiPragmaticFootballBlitzSpinsRoute
  '/api/roulette/spins': typeof ApiRouletteSpinsRoute
  '/api/roulette/strategy-global': typeof ApiRouletteStrategyGlobalRouteWithChildren
  '/api/roulette/strategy-global/reset': typeof ApiRouletteStrategyGlobalResetRoute
  '/api/roulette/strategy-global/stream': typeof ApiRouletteStrategyGlobalStreamRoute
  '/mobile/roleta/$mesaId/dois2fatores': typeof MobileRoletaMesaIdDois2fatoresRoute
  '/mobile/roleta/$mesaId/um1fator': typeof MobileRoletaMesaIdUm1fatorRoute
  '/mobile/roleta/$mesaId/': typeof MobileRoletaMesaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casino-mesa'
    | '/damas'
    | '/doc-calculadora-roulette'
    | '/dois-fatores'
    | '/football-blitz'
    | '/mobile'
    | '/numeros-28pct'
    | '/ruas'
    | '/ruas-10pct'
    | '/ruas-25pct'
    | '/sala-rotativa'
    | '/sala-rotativa-um-fator'
    | '/smart-move'
    | '/super-trunfo'
    | '/tres-fatores'
    | '/um-fator'
    | '/api/damas'
    | '/api/events'
    | '/api/raw'
    | '/mobile/dois2fatores'
    | '/mobile/perfil'
    | '/mobile/um1fator'
    | '/mobile/'
    | '/api/pragmatic/24d-spin-spins'
    | '/api/pragmatic/football-blitz-spins'
    | '/api/roulette/spins'
    | '/api/roulette/strategy-global'
    | '/api/roulette/strategy-global/reset'
    | '/api/roulette/strategy-global/stream'
    | '/mobile/roleta/$mesaId/dois2fatores'
    | '/mobile/roleta/$mesaId/um1fator'
    | '/mobile/roleta/$mesaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casino-mesa'
    | '/damas'
    | '/doc-calculadora-roulette'
    | '/dois-fatores'
    | '/football-blitz'
    | '/numeros-28pct'
    | '/ruas'
    | '/ruas-10pct'
    | '/ruas-25pct'
    | '/sala-rotativa'
    | '/sala-rotativa-um-fator'
    | '/smart-move'
    | '/super-trunfo'
    | '/tres-fatores'
    | '/um-fator'
    | '/api/damas'
    | '/api/events'
    | '/api/raw'
    | '/mobile/dois2fatores'
    | '/mobile/perfil'
    | '/mobile/um1fator'
    | '/mobile'
    | '/api/pragmatic/24d-spin-spins'
    | '/api/pragmatic/football-blitz-spins'
    | '/api/roulette/spins'
    | '/api/roulette/strategy-global'
    | '/api/roulette/strategy-global/reset'
    | '/api/roulette/strategy-global/stream'
    | '/mobile/roleta/$mesaId/dois2fatores'
    | '/mobile/roleta/$mesaId/um1fator'
    | '/mobile/roleta/$mesaId'
  id:
    | '__root__'
    | '/'
    | '/casino-mesa'
    | '/damas'
    | '/doc-calculadora-roulette'
    | '/dois-fatores'
    | '/football-blitz'
    | '/mobile'
    | '/numeros-28pct'
    | '/ruas'
    | '/ruas-10pct'
    | '/ruas-25pct'
    | '/sala-rotativa'
    | '/sala-rotativa-um-fator'
    | '/smart-move'
    | '/super-trunfo'
    | '/tres-fatores'
    | '/um-fator'
    | '/api/damas'
    | '/api/events'
    | '/api/raw'
    | '/mobile/dois2fatores'
    | '/mobile/perfil'
    | '/mobile/um1fator'
    | '/mobile/'
    | '/api/pragmatic/24d-spin-spins'
    | '/api/pragmatic/football-blitz-spins'
    | '/api/roulette/spins'
    | '/api/roulette/strategy-global'
    | '/api/roulette/strategy-global/reset'
    | '/api/roulette/strategy-global/stream'
    | '/mobile/roleta/$mesaId/dois2fatores'
    | '/mobile/roleta/$mesaId/um1fator'
    | '/mobile/roleta/$mesaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasinoMesaRoute: typeof CasinoMesaRoute
  DamasRoute: typeof DamasRoute
  DocCalculadoraRouletteRoute: typeof DocCalculadoraRouletteRoute
  DoisFatoresRoute: typeof DoisFatoresRoute
  FootballBlitzRoute: typeof FootballBlitzRoute
  MobileRoute: typeof MobileRouteWithChildren
  Numeros28pctRoute: typeof Numeros28pctRoute
  RuasRoute: typeof RuasRoute
  Ruas10pctRoute: typeof Ruas10pctRoute
  Ruas25pctRoute: typeof Ruas25pctRoute
  SalaRotativaRoute: typeof SalaRotativaRoute
  SalaRotativaUmFatorRoute: typeof SalaRotativaUmFatorRoute
  SmartMoveRoute: typeof SmartMoveRoute
  SuperTrunfoRoute: typeof SuperTrunfoRoute
  TresFatoresRoute: typeof TresFatoresRoute
  UmFatorRoute: typeof UmFatorRoute
  ApiDamasRoute: typeof ApiDamasRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiRawRoute: typeof ApiRawRoute
  ApiPragmatic24dSpinSpinsRoute: typeof ApiPragmatic24dSpinSpinsRoute
  ApiPragmaticFootballBlitzSpinsRoute: typeof ApiPragmaticFootballBlitzSpinsRoute
  ApiRouletteSpinsRoute: typeof ApiRouletteSpinsRoute
  ApiRouletteStrategyGlobalRoute: typeof ApiRouletteStrategyGlobalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/um-fator': {
      id: '/um-fator'
      path: '/um-fator'
      fullPath: '/um-fator'
      preLoaderRoute: typeof UmFatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tres-fatores': {
      id: '/tres-fatores'
      path: '/tres-fatores'
      fullPath: '/tres-fatores'
      preLoaderRoute: typeof TresFatoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-trunfo': {
      id: '/super-trunfo'
      path: '/super-trunfo'
      fullPath: '/super-trunfo'
      preLoaderRoute: typeof SuperTrunfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-move': {
      id: '/smart-move'
      path: '/smart-move'
      fullPath: '/smart-move'
      preLoaderRoute: typeof SmartMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala-rotativa-um-fator': {
      id: '/sala-rotativa-um-fator'
      path: '/sala-rotativa-um-fator'
      fullPath: '/sala-rotativa-um-fator'
      preLoaderRoute: typeof SalaRotativaUmFatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala-rotativa': {
      id: '/sala-rotativa'
      path: '/sala-rotativa'
      fullPath: '/sala-rotativa'
      preLoaderRoute: typeof SalaRotativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas-25pct': {
      id: '/ruas-25pct'
      path: '/ruas-25pct'
      fullPath: '/ruas-25pct'
      preLoaderRoute: typeof Ruas25pctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas-10pct': {
      id: '/ruas-10pct'
      path: '/ruas-10pct'
      fullPath: '/ruas-10pct'
      preLoaderRoute: typeof Ruas10pctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas': {
      id: '/ruas'
      path: '/ruas'
      fullPath: '/ruas'
      preLoaderRoute: typeof RuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros-28pct': {
      id: '/numeros-28pct'
      path: '/numeros-28pct'
      fullPath: '/numeros-28pct'
      preLoaderRoute: typeof Numeros28pctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football-blitz': {
      id: '/football-blitz'
      path: '/football-blitz'
      fullPath: '/football-blitz'
      preLoaderRoute: typeof FootballBlitzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dois-fatores': {
      id: '/dois-fatores'
      path: '/dois-fatores'
      fullPath: '/dois-fatores'
      preLoaderRoute: typeof DoisFatoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-calculadora-roulette': {
      id: '/doc-calculadora-roulette'
      path: '/doc-calculadora-roulette'
      fullPath: '/doc-calculadora-roulette'
      preLoaderRoute: typeof DocCalculadoraRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damas': {
      id: '/damas'
      path: '/damas'
      fullPath: '/damas'
      preLoaderRoute: typeof DamasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-mesa': {
      id: '/casino-mesa'
      path: '/casino-mesa'
      fullPath: '/casino-mesa'
      preLoaderRoute: typeof CasinoMesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/um1fator': {
      id: '/mobile/um1fator'
      path: '/um1fator'
      fullPath: '/mobile/um1fator'
      preLoaderRoute: typeof MobileUm1fatorRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/perfil': {
      id: '/mobile/perfil'
      path: '/perfil'
      fullPath: '/mobile/perfil'
      preLoaderRoute: typeof MobilePerfilRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/dois2fatores': {
      id: '/mobile/dois2fatores'
      path: '/dois2fatores'
      fullPath: '/mobile/dois2fatores'
      preLoaderRoute: typeof MobileDois2fatoresRouteImport
      parentRoute: typeof MobileRoute
    }
    '/api/raw': {
      id: '/api/raw'
      path: '/api/raw'
      fullPath: '/api/raw'
      preLoaderRoute: typeof ApiRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/damas': {
      id: '/api/damas'
      path: '/api/damas'
      fullPath: '/api/damas'
      preLoaderRoute: typeof ApiDamasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roulette/strategy-global': {
      id: '/api/roulette/strategy-global'
      path: '/api/roulette/strategy-global'
      fullPath: '/api/roulette/strategy-global'
      preLoaderRoute: typeof ApiRouletteStrategyGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roulette/spins': {
      id: '/api/roulette/spins'
      path: '/api/roulette/spins'
      fullPath: '/api/roulette/spins'
      preLoaderRoute: typeof ApiRouletteSpinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pragmatic/football-blitz-spins': {
      id: '/api/pragmatic/football-blitz-spins'
      path: '/api/pragmatic/football-blitz-spins'
      fullPath: '/api/pragmatic/football-blitz-spins'
      preLoaderRoute: typeof ApiPragmaticFootballBlitzSpinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pragmatic/24d-spin-spins': {
      id: '/api/pragmatic/24d-spin-spins'
      path: '/api/pragmatic/24d-spin-spins'
      fullPath: '/api/pragmatic/24d-spin-spins'
      preLoaderRoute: typeof ApiPragmatic24dSpinSpinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/roleta/$mesaId/': {
      id: '/mobile/roleta/$mesaId/'
      path: '/roleta/$mesaId'
      fullPath: '/mobile/roleta/$mesaId/'
      preLoaderRoute: typeof MobileRoletaMesaIdIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/roleta/$mesaId/um1fator': {
      id: '/mobile/roleta/$mesaId/um1fator'
      path: '/roleta/$mesaId/um1fator'
      fullPath: '/mobile/roleta/$mesaId/um1fator'
      preLoaderRoute: typeof MobileRoletaMesaIdUm1fatorRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/roleta/$mesaId/dois2fatores': {
      id: '/mobile/roleta/$mesaId/dois2fatores'
      path: '/roleta/$mesaId/dois2fatores'
      fullPath: '/mobile/roleta/$mesaId/dois2fatores'
      preLoaderRoute: typeof MobileRoletaMesaIdDois2fatoresRouteImport
      parentRoute: typeof MobileRoute
    }
    '/api/roulette/strategy-global/stream': {
      id: '/api/roulette/strategy-global/stream'
      path: '/stream'
      fullPath: '/api/roulette/strategy-global/stream'
      preLoaderRoute: typeof ApiRouletteStrategyGlobalStreamRouteImport
      parentRoute: typeof ApiRouletteStrategyGlobalRoute
    }
    '/api/roulette/strategy-global/reset': {
      id: '/api/roulette/strategy-global/reset'
      path: '/reset'
      fullPath: '/api/roulette/strategy-global/reset'
      preLoaderRoute: typeof ApiRouletteStrategyGlobalResetRouteImport
      parentRoute: typeof ApiRouletteStrategyGlobalRoute
    }
  }
}

interface MobileRouteChildren {
  MobileDois2fatoresRoute: typeof MobileDois2fatoresRoute
  MobilePerfilRoute: typeof MobilePerfilRoute
  MobileUm1fatorRoute: typeof MobileUm1fatorRoute
  MobileIndexRoute: typeof MobileIndexRoute
  MobileRoletaMesaIdDois2fatoresRoute: typeof MobileRoletaMesaIdDois2fatoresRoute
  MobileRoletaMesaIdUm1fatorRoute: typeof MobileRoletaMesaIdUm1fatorRoute
  MobileRoletaMesaIdIndexRoute: typeof MobileRoletaMesaIdIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileDois2fatoresRoute: MobileDois2fatoresRoute,
  MobilePerfilRoute: MobilePerfilRoute,
  MobileUm1fatorRoute: MobileUm1fatorRoute,
  MobileIndexRoute: MobileIndexRoute,
  MobileRoletaMesaIdDois2fatoresRoute: MobileRoletaMesaIdDois2fatoresRoute,
  MobileRoletaMesaIdUm1fatorRoute: MobileRoletaMesaIdUm1fatorRoute,
  MobileRoletaMesaIdIndexRoute: MobileRoletaMesaIdIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface ApiRouletteStrategyGlobalRouteChildren {
  ApiRouletteStrategyGlobalResetRoute: typeof ApiRouletteStrategyGlobalResetRoute
  ApiRouletteStrategyGlobalStreamRoute: typeof ApiRouletteStrategyGlobalStreamRoute
}

const ApiRouletteStrategyGlobalRouteChildren: ApiRouletteStrategyGlobalRouteChildren =
  {
    ApiRouletteStrategyGlobalResetRoute: ApiRouletteStrategyGlobalResetRoute,
    ApiRouletteStrategyGlobalStreamRoute: ApiRouletteStrategyGlobalStreamRoute,
  }

const ApiRouletteStrategyGlobalRouteWithChildren =
  ApiRouletteStrategyGlobalRoute._addFileChildren(
    ApiRouletteStrategyGlobalRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasinoMesaRoute: CasinoMesaRoute,
  DamasRoute: DamasRoute,
  DocCalculadoraRouletteRoute: DocCalculadoraRouletteRoute,
  DoisFatoresRoute: DoisFatoresRoute,
  FootballBlitzRoute: FootballBlitzRoute,
  MobileRoute: MobileRouteWithChildren,
  Numeros28pctRoute: Numeros28pctRoute,
  RuasRoute: RuasRoute,
  Ruas10pctRoute: Ruas10pctRoute,
  Ruas25pctRoute: Ruas25pctRoute,
  SalaRotativaRoute: SalaRotativaRoute,
  SalaRotativaUmFatorRoute: SalaRotativaUmFatorRoute,
  SmartMoveRoute: SmartMoveRoute,
  SuperTrunfoRoute: SuperTrunfoRoute,
  TresFatoresRoute: TresFatoresRoute,
  UmFatorRoute: UmFatorRoute,
  ApiDamasRoute: ApiDamasRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiRawRoute: ApiRawRoute,
  ApiPragmatic24dSpinSpinsRoute: ApiPragmatic24dSpinSpinsRoute,
  ApiPragmaticFootballBlitzSpinsRoute: ApiPragmaticFootballBlitzSpinsRoute,
  ApiRouletteSpinsRoute: ApiRouletteSpinsRoute,
  ApiRouletteStrategyGlobalRoute: ApiRouletteStrategyGlobalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
